sudo: required
dist: trusty
services:
  - docker
language: python
env:
  - TEST_MODE=run_program
python:
  - "2.7"
  - "3.3"
  - "3.5"
  - "3.6"
install: .travis/install.sh
script: .travis/test.sh
after_success: .travis/finish.sh
matrix:
  include:
    - dist: trusty
      python: "2.7"
      env: TEST_MODE=checks
    - dist: trusty
      python: "2.7"
      env: TEST_MODE=coverage
  exclude:
    # This is already tested by coverage
    - python: "2.7"
      env: TEST_MODE=run_program
