sudo: required
services:
  - docker
language: python
env:
  - TEST_MODE=run_program
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install: .travis/install.sh
script: .travis/test.sh
after_success: .travis/finish.sh
matrix:
  include:
    - python: "2.7"
      env: TEST_MODE=checks
    - python: "2.7"
      env: TEST_MODE=coverage
  exclude:
    # This is already tested by coverage
    - python: "2.7"
      env: TEST_MODE=run_program
